// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// EmployeeHandler is an autogenerated mock type for the EmployeeHandler type
type EmployeeHandler struct {
	mock.Mock
}

// HandleAllEmployeesRequest provides a mock function with given fields: _a0, _a1
func (_m *EmployeeHandler) HandleAllEmployeesRequest(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// HandleAllEmployeesRetrieval provides a mock function with given fields: _a0
func (_m *EmployeeHandler) HandleAllEmployeesRetrieval(_a0 http.ResponseWriter) {
	_m.Called(_a0)
}

// HandleEmployeeCreation provides a mock function with given fields: _a0, _a1
func (_m *EmployeeHandler) HandleEmployeeCreation(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// HandleEmployeeDeletion provides a mock function with given fields: _a0, _a1
func (_m *EmployeeHandler) HandleEmployeeDeletion(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// HandleEmployeeRequest provides a mock function with given fields: _a0, _a1
func (_m *EmployeeHandler) HandleEmployeeRequest(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// HandleEmployeeUpdate provides a mock function with given fields: _a0, _a1
func (_m *EmployeeHandler) HandleEmployeeUpdate(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// NewEmployeeHandler creates a new instance of EmployeeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeHandler {
	mock := &EmployeeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
